go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md
go test ./test/host_test.go -run TestMoreHosts -v > ./test_logs/$(get-date -f dd-hh-mm-ss).md